name: aviation_entities

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  aviation_units:
    path: ../aviation_units
  collection: ^1.17.1
  freezed_annotation: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^2.1.0+1
  json_serializable: ^6.0.1
  lint: ^2.1.2
  test: ^1.24.2
