name: aviation_entities

environment:
  sdk: ">=2.14.0<3.0.0"

dependencies:
  aviation_units:
    path: ../aviation_units
  freezed_annotation: ^0.14.3
  lint: ^1.8.2
  shared_dart:
    path: ../shared_dart

dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^0.14.5
  test: ^1.16.8
