name: aviation_entities

environment:
  sdk: ">=2.14.0<3.0.0"

dependencies:
  aviation_units:
    path: ../aviation_units
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^1.1.0
  json_serializable: ^6.0.1
  lint: ^1.8.2
  test: ^1.19.0
