name: aviation_entities

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  aviation_units:
    path: ../aviation_units
  collection: ^1.18.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lint: ^2.1.2
  test: ^1.8.3
